- name: Apt install bind9
  ansible.builtin.apt:
    name:
      - bind9
      - rsync
    update_cache: true

- name: Copy template of bind9
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/bind/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - "named.conf.options"

- name: Synchronize configs of bind
  ansible.posix.synchronize:
    src: "files/{{ inventory_hostname }}/bind"
    dest: "/etc/"
  notify:
    - Chown bind
    - Restart bind
  tags:
    - bind_config
