- name: Chown bind files
  ansible.builtin.file:
    path: /etc/bind
    owner: bind
    group: bind
    recurse: true
  listen: Chown bind

- name: Chown bind path
  ansible.builtin.file:
    path: /etc/bind
    owner: bind
    group: bind
    mode: '0750'
  listen: Chown bind

- name: Restart bind
  ansible.builtin.service:
    name: bind9
    state: restarted
  tags:
    - bind_restart
